name: EPUB

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://pandoc/core:latest
      with:
        args: cd src && pandoc *.md -f markdown -t epub -s -o think-like-a-git.epub
    - uses: actions/upload-artifact@v1
      with:
        name: think-like-a-git
        path: think-like-a-git.epub
