name: EPUB

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: "awk 'FNR==1{print ""}1' src/*.md > think-like-a-git.md"
      - uses: docker://pandoc/core:latest
        with:
          args: "think-like-a-git.md --resource-path=.:src -f markdown -t epub -s -o think-like-a-git.epub"
      - uses: actions/upload-artifact@v1
        with:
          name: think-like-a-git
          path: think-like-a-git.epub